// Sample data for migration and testing
export const sampleClients = [
  {
    clientId: "CID5962",
    accountName: "Goldman Sachs International",
    accountNumber: "GSI-UK-001",
    principalEntity: "Goldman Sachs International",
    lei: "W22LROWP2IHZNBB6K528",
    domicile: "United Kingdom",
    threshold: 5000000,
    reportingCurrency: "USD",
    mta: { amount: 100000, currency: "USD" },
    assets: ["Cash", "Government Bonds", "Corporate Bonds"],
    currencies: ["USD", "EUR", "GBP"],
    holidays: ["UK", "US"],
    contact: { phone: "+44 20 7774 1000", email: "collateral@goldmansachs.com" },
    notificationTime: "09:00 GMT",
    settlementPeriod: "T+1",
  },
  {
    clientId: "CID2693",
    accountName: "Morgan Stanley & Co. International",
    accountNumber: "MSI-UK-002",
    principalEntity: "Morgan Stanley & Co. International plc",
    lei: "4PQUHN3JPFGFNF3BB653",
    domicile: "United Kingdom",
    threshold: 3000000,
    reportingCurrency: "USD",
    mta: { amount: 75000, currency: "USD" },
    assets: ["Cash", "Government Bonds"],
    currencies: ["USD", "EUR"],
    holidays: ["UK", "US"],
    contact: { phone: "+44 20 7425 8000", email: "margin@morganstanley.com" },
    notificationTime: "08:30 GMT",
    settlementPeriod: "T+1",
  },
  {
    clientId: "CID5299",
    accountName: "JPMorgan Securities plc",
    accountNumber: "JPM-UK-003",
    principalEntity: "JPMorgan Securities plc",
    lei: "XKZZ2JZF41MRHTR1V493",
    domicile: "United Kingdom",
    threshold: 4000000,
    reportingCurrency: "USD",
    mta: { amount: 125000, currency: "USD" },
    assets: ["Cash", "Government Bonds", "Corporate Bonds", "Equities"],
    currencies: ["USD", "EUR", "GBP", "CHF"],
    holidays: ["UK", "US", "CH"],
    contact: { phone: "+44 20 7742 6000", email: "collateral@jpmorgan.com" },
    notificationTime: "09:15 GMT",
    settlementPeriod: "T+1",
  },
]

export const sampleMarginCalls = [
  {
    clientId: "CID5962",
    counterparty: "Barclays",
    callAmount: 1200000,
    currency: "USD",
    exposure: 15000000,
    bookingStatus: "Fully Booked",
    disputeAmount: 0,
    priceMovement: -0.8,
    bookingType: "Acadia-Electronic",
    direction: "inbound" as const,
    date: new Date(),
  },
  {
    clientId: "CID2693",
    counterparty: "Barclays",
    callAmount: 850000,
    currency: "EUR",
    exposure: 12000000,
    bookingStatus: "Fully Booked",
    disputeAmount: 0,
    priceMovement: -0.5,
    bookingType: "Manual",
    direction: "outbound" as const,
    date: new Date(),
  },
  {
    clientId: "CID5299",
    counterparty: "Barclays",
    callAmount: 2000000,
    currency: "GBP",
    exposure: 25000000,
    bookingStatus: "Fully Disputed",
    disputeAmount: 2000000,
    priceMovement: 1.2,
    bookingType: "Manual",
    disputeReason: "MTM Mismatch",
    direction: "inbound" as const,
    date: new Date(),
  },
]

export const sampleDailyActivities = [
  {
    clientId: "CID5962",
    activityType: "Margin Call Issued",
    amount: 1200000,
    currency: "USD",
    status: "Completed",
    date: new Date(),
  },
  {
    clientId: "CID2693",
    activityType: "Collateral Received",
    amount: 850000,
    currency: "EUR",
    status: "Completed",
    date: new Date(),
  },
  {
    clientId: "CID5299",
    activityType: "Dispute Raised",
    amount: 2000000,
    currency: "GBP",
    status: "Pending",
    date: new Date(),
  },
] 